# Generated by Django 5.0.2 on 2024-03-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='planned_delivery_date',
            field=models.CharField(default='2024-02-12', max_length=200),
        ),
    ]
