# Generated by Django 5.0.2 on 2024-03-05 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InTransit', 'In Transit'), ('Delivered', 'Delivered'), ('on hold', 'on hold')], default='Pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.parcel')),
            ],
        ),
    ]
